# Generated by Django 3.1.7 on 2021-03-13 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0003_auto_20210310_1658'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokemonentity',
            old_name='model',
            new_name='level',
        ),
    ]
